version: '3.8'

services:
  backend:
    build: ./app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app
      - ./data:/data

  frontend:
    build: ./app/frontend
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app
    depends_on:
      - backend
